using Volo.Abp;

namespace SpaceOfNationalRoad107Taoist.EntityFrameworkCore;

public abstract class SpaceOfNationalRoad107TaoistEntityFrameworkCoreTestBase : SpaceOfNationalRoad107TaoistTestBase<SpaceOfNationalRoad107TaoistEntityFrameworkCoreTestModule>
{

}
