namespace SpaceOfNationalRoad107Taoist;

public abstract class SpaceOfNationalRoad107TaoistApplicationTestBase : SpaceOfNationalRoad107TaoistTestBase<SpaceOfNationalRoad107TaoistApplicationTestModule>
{

}
